# Convert to csv

This code is used to convert the data of Chambon from: https://github.com/spalminteri/agency.git in _original_

Each file contains a matrix M, which corresponds to the data of one participant. 
There were 24 participants in the first experiment;

In the matrix M, each line corresponds to one trial. 

Each column refers to:

- column 1: the session number. Each experiment contains different sessions, with 4 blocks corresponding to the 4 experimental conditions. Participants had a break between each session.

- column 2: the condition number. Conditions 1 and 2 correspond to high-reward blocks (reward probabilities were 90% and 60% for the two symbols). Conditions 3 and 4 correspond to low-reward blocks (reward probabilities were 40% and 10%). In the first experiment, conditions 1 and 3 correspond to blocks with only free-choice trials, while in conditions 2 and 4 free- and forced-choice trials were intermixed within the block. In the second experiment, conditions 1 and 3 correspond to trials in which only the factual outcome was shown, while both the factual and counterfactual outcomes were shown in conditions 2 and 4.

- column 3: the trial number within a block, e.g. 1 corresponds to the first trial of a block, the trial in which the participants sees a given pair of symbols for the first time.

- column 4: the outcome of the best rewarded stimulus. The outcomes could either be +1 or -1. « 0 » indicates that the trial was a forced-choice trial - the best rewarded symbol was not shown to the participant in this trial.

- column 5: the outcome of the least rewarded symbol. The outcomes could either be 1 (the participant wins one point) or -1 (the participant lost one point). "0" indicates that the trial was a forced-choice trial, and that the least rewarded symbol was not shown to the participant in this trial.

- column 6: the participant's choice. "1" indicates that the participant has chosen the best rewarded symbol, and "0" that she has chosen the least rewarded symbol.

- column 7: whether the trial was a free choice (1) or a forced choice (0). For experiment 4, this column indicates whether the trial was a "go" (-1) or a "no-go" (1) trial. 

- column 8: the reaction time for selecting the symbol

- column 9: the reaction time for confirming the outcome (see experimental protocol).

In [4]:
24 * 3

72

In [3]:
3 *240

720

In [ ]:
import numpy as np
import scipy
import scipy.io
import pandas as pd

## Population definition
n_subj = 24
n_trials = 720 # 3 * 240 trials (per condition)
               # 240 trials -> 2 * 80 forced, 2 * 40 free 

## Define DataFrame

columns=['participant_number', # participant number
         'session_number', # experimental session (1,2,3)
         'condition_number', # conditions 1, 2 -> high rew, condition 3, 4 -> low rew, condition 1,3 only free choice trials, condition 2, 4 free/forced intermixed
         'trial_number', # trials within a block
         'outcome_best_rewarded', # outcome of best rewarded symbol (1 = win, -1=lost, 0=forced_choice no best rewarded symbol shown)
         'outcome_least_rewarded', # outcome of least rewarded symbol (1 = win, -1=lost, 0=forced_choice no least rewarded symbol shown)
         'participants_choice', # 1 for optimal action, 0 for suboptimal action
         'free_forced_choice_trial', # 1 for free, 0 for forced
         'RT',
         'RT_choice']

df = pd.DataFrame(columns=columns)

for part in range(24):
    part += 1
    path = 'original/Experiment1/'

    data = scipy.io.loadmat(path + 'passymetrieI_Suj' + str(part) + '.mat')
    data = data['M']

    temp_df = pd.DataFrame({
                        'participant_number': np.repeat(part, n_trials),
                        'session_number': data[:,0],
                        'condition_number': data[:,1],
                        'trial_number': data[:,2],
                        'outcome_best_rewarded': data[:,3],
                        'outcome_least_rewarded': data[:,4],
                        'participants_choice': data[:,5],
                        'free_forced_choice_trial': data[:,6],
                        'RT': data[:,7],
                        'RT_choice': data[:,8]})

    df = pd.concat([df, temp_df], ignore_index=True)

df.condition_number.unique()

In [2]:
df.to_csv('exp1.csv', index=False)

In [4]:
import pandas as pd

df = pd.read_csv('exp1.csv')

p = df[df.participant_number == 1]
p # 240 per session, 4 conditions, 80*2 + 40*2 trials


pd.set_option('display.max_rows', 720)




In [2]:
240 * 3

720

In [4]:
df[(df.participant_number == 1) & (df.session_number == 1) & (df.condition_number == 2)].head(20)

participant_number  session_number  condition_number  trial_number  \
40                  1             1.0               2.0           1.0   
41                  1             1.0               2.0           2.0   
42                  1             1.0               2.0           3.0   
43                  1             1.0               2.0           4.0   
44                  1             1.0               2.0           5.0   
45                  1             1.0               2.0           6.0   
46                  1             1.0               2.0           7.0   
47                  1             1.0               2.0           8.0   
48                  1             1.0               2.0           9.0   
49                  1             1.0               2.0          10.0   
50                  1             1.0               2.0          11.0   
51                  1             1.0               2.0          12.0   
52                  1             1.0               2.0          13.0   
53                  1             1.0               2.0          14.0   
54                  1             1.0               2.0          15.0   
55                  1             1.0               2.0          16.0   
56                  1             1.0               2.0          17.0   
57                  1             1.0               2.0          18.0   
58                  1             1.0               2.0          19.0   
59                  1             1.0               2.0          20.0   

    outcome_best_rewarded  outcome_least_rewarded  participants_choice  \
40                    0.0                     1.0                  0.0   
41                    1.0                    -1.0                  1.0   
42                    1.0                     1.0                  1.0   
43                    1.0                     1.0                  0.0   
44                    1.0                     0.0                  1.0   
45                    0.0                    -1.0                  0.0   
46                    1.0                     1.0                  1.0   
47                    1.0                     1.0                  1.0   
48                    1.0                     1.0                  0.0   
49                    1.0                     0.0                  1.0   
50                    0.0                     1.0                  0.0   
51                    0.0                    -1.0                  0.0   
52                    1.0                    -1.0                  1.0   
53                    0.0                     1.0                  0.0   
54                   -1.0                     0.0                  1.0   
55                    0.0                    -1.0                  0.0   
56                    1.0                     1.0                  0.0   
57                    1.0                    -1.0                  0.0   
58                    0.0                    -1.0                  0.0   
59                    1.0                     1.0                  1.0   

    free_forced_choice_trial        RT  RT_choice  
40                       0.0  0.497014   0.000819  
41                       1.0  0.520654   0.000798  
42                       1.0  0.218038   0.000418  
43                       1.0  1.244883   0.000398  
44                       0.0  0.550903   0.106341  
45                       0.0  0.483395   0.490750  
46                       1.0  0.359403   0.374935  
47                       1.0  0.000792   0.255770  
48                       1.0  0.279782   0.000804  
49                       0.0  0.901779   0.000766  
50                       0.0  1.248468   0.000804  
51                       0.0  0.565268   0.001226  
52                       1.0  0.350059   0.392010  
53                       0.0  0.630437   0.031086  
54                       0.0  0.743809   0.092769  
55                       0.0  0.327541   0.325370  
56                       1.0  

In [10]:
df[df.participant_number == 2].describe()

participant_number  session_number  condition_number  trial_number  \
count               720.0      720.000000        720.000000    720.000000   
mean                  2.0        2.000000          2.666667     33.833333   
std                   0.0        0.817064          1.106310     22.124317   
min                   2.0        1.000000          1.000000      1.000000   
25%                   2.0        1.000000          2.000000     15.750000   
50%                   2.0        2.000000          2.500000     30.500000   
75%                   2.0        3.000000          4.000000     50.250000   
max                   2.0        3.000000          4.000000     80.000000   

       outcome_best_rewarded  outcome_least_rewarded  participants_choice  \
count             720.000000              720.000000           720.000000   
mean                0.250000               -0.250000             0.777778   
std                 0.878581                0.878581             0.416029   
min                -1.000000               -1.000000             0.000000   
25%                -1.000000               -1.000000             1.000000   
50%                 1.000000               -1.000000             1.000000   
75%                 1.000000                1.000000             1.000000   
max                 1.000000                1.000000             1.000000   

       free_forced_choice_trial          RT   RT_choice  
count                720.000000  720.000000  720.000000  
mean                   0.666667    0.333058    0.125853  
std                    0.471732    0.535031    0.256974  
min                    0.000000    0.000898    0.000893  
25%                    0.000000    0.005237    0.001551  
50%                    1.000000    0.256951    0.014202  
75%                    1.000000    0.412440    0.162858  
max                    1.000000    5.755169    2.607059

In [65]:
# check wether conditions are randomized
for j in range(3):
    j += 1
    p = df[df.participant_number == j]

    print(j)
    for i in range(3):
        i += 1
        d = p[p.session_number == i]
        print(d['condition_number'].unique())

1
[3. 4. 1. 2.]
[1. 4. 3. 2.]
[4. 3. 1. 2.]
2
[3. 4. 1. 2.]
[1. 4. 3. 2.]
[4. 3. 1. 2.]
3
[3. 4. 1. 2.]
[1. 4. 3. 2.]
[4. 3. 1. 2.]


In [34]:
# 1, 3 free choice
df = p[(p.condition_number == 1) | (p.condition_number == 3)]
df['free_forced_choice_trial'].value_counts()

1.0    240
Name: free_forced_choice_trial, dtype: int64

In [38]:
# 2, 4 free/forced intermixed
df = p[(p.condition_number == 2) | (p.condition_number == 4)]
df['free_forced_choice_trial'].value_counts()

1.0    240
0.0    240
Name: free_forced_choice_trial, dtype: int64

-> 3 sessions, in between breaks
-> 4 conditions per sesssion:
    - condition 1, 3 free choice: 40 * 2
    - condition 2, 4 free/forced intermixed: 80 * 2 (40 free, 40 forced)

(sessions have conditions randomly intermixed)
(free force choice randomly intermixed)


forced choice was visible by inidcati